name: Secrets
on: push
jobs:
  secret-env-vars:
    runs-on: self-hosted
    steps:
      - name: Secrets
        run: |
            echo ${{ secrets.MONGO_URI }}  
        env: 
            MONGO_URI: ${{ secrets.MONGO_URI }}
            PORT: ${{ secrets.PORT }}
            TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}